---
- hosts: cluster
  become: yes

  vars_files:
    - vars/main.yml

  vars:
    list_of_packages:
      - nfs-common
        
  tasks:
    - name: Install common NFS packages
      package:
        name: "{{ list_of_packages }}"
        state: latest

    - name: Create NFS directory
      file:
        path: "{{ nfs_dir }}"
        state: directory
        owner: root
        group: root
        mode: '1777'
